project:
  type: website

website:
  title: "PM 566"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - syllabus.qmd
      - schedule.qmd
      - references.qmd
  page-footer: 
    left:
      University of Southern California <br>
      Department of Population and Public Health Sciences
    right:
      LICENSE <br>
      View the source at GitHub.
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



